name: Prosperity2BT Conversion

on:
  push:
    paths:
      - '**/*.py' # This pattern is for Python files

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install prosperity2bt
      run: pip install -U prosperity2bt

    - name: Find and Convert File
      run: |
        commit_count=$(git rev-list --count HEAD)
        if [[ $commit_count -gt 1 ]]; then
          for file in $(git diff --name-only HEAD~1); do
            if [[ $file == *.py ]]; then # Ensure it matches your expected file types, now looking for Python files
              echo "Converting $file..."
              prosperity2bt $file 1
            fi
          done
        else
          echo "Not enough commits for a diff. Processing all *.py files."
          for file in $(find . -type f -name "*.py"); do
            echo "Converting $file..."
            prosperity2bt "$file" 1
          done
        fi
